sonar.projectKey=Berkilic41_leave-system
sonar.organization=berkilic41
sonar.projectName=Employee & Leave Management System
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/obj/**,**/bin/**

sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.cs.vstest.reportsPaths=**/test-results.trx
